FROM maven:3.9-eclipse-temurin-17-alpine AS build
WORKDIR /workspace
COPY service-registry/pom.xml ./pom.xml
COPY service-registry/src ./src
RUN mvn package -DskipTests -q

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /workspace/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "app.jar"]
